version: "3.7"
services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432 
    environment:
      POSTGRES_USER: banana
      POSTGRES_PASSWORD: banana
    volumes:
      - $PWD/data:/var/lib/postgresql/data
